language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    rooms:
      secure: Pyqq6m1x7zYvvw9wCGx7vBhZxsjGK3oUGhamNMSiScq6/xYBZZ3M6bLRy5SwFCsGSmIQZe+liAzHRAInDlPWExEadWKgDPJgj+6qQICWdNP5wTqjVZBzXHHHgzcX7OEFAuZ59xSF2Q3fG1pjzgrpumDBXhdKWnsUBwMn/EcAG7ckdszirLRiIXyDDQ2++t8D4Sp8Qam5YvBQGN5oHQN94CkfsReV8WZxmyQHpAid+Nd68CniQEnFI3iu2+i9MhGJzEoTvNx4lqoPfXdquTTkFBbFSq/DVVgxdCKRyAse+HOl+5BIoz338632RWLqaRVWCTyvG/12OgSKfKv279y2+lPIkoplyUtAt/haBlOcZBOzfvkVB0NqSFjS0SXFG3GD9ev9C4faCOYanaRgpWFfCI+LPrXrwL/G8wAsbRQsjUrOBGa+1GY00uSnSFZ4irg4iIGL/o0kO2zZ6q/F6lokWtho2qTGp/Pby1JemlxAPeZrt0K1UshPfwB7c2DMan66qO3La1+hAmLyowWwNNKo/g4E1XcRSfKkxAQPkqWYlMwEjwoBWhdciyDGZWazgzVy/g9gLQKP8pOHob3Q5OiIcKBPbPnbpZoE27Zcv5Mf/KF1WisF3H2vKS6+m4W9tRVpnGGw8mjROO4G3MWE0TUa1l3k7XI50kGeGYlJaiUnYMo=
node_js:
- '8'
before_script:
- npm prune
script:
- npm t
- npm run _build
after_success:
- |
  if [ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]; then
    npm run _semantic-release && npm run _report && npm run _documentation
  fi
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
